name: SonarCloud Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=my_project --cov-report=xml

      - name: Verify coverage file exists
        run: ls -lah coverage.xml  # Debug step to check if coverage.xml is generated

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=soult
            -Dsonar.projectKey=pavankumar2107_soultrepo
            -Dsonar.python.version=3.10
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
